openapi: 3.0.0
info:
  title: API Argent Bank
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
security:
  - bearerAuth: []
paths:
  /user/login:
    post:
      summary: Authentifier un utilisateur
      description: Retourne un token JWT si les identifiants sont valides.
      tags:
        - Authentification
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: tony@stark.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Identifiants invalides
  /user/profile:
    get:
      summary: Récupérer le profil utilisateur
      description: Retourne les informations du profil de l'utilisateur authentifié.
      responses:
        '200':
          description: Profil utilisateur récupéré
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
        '401':
          description: Non authentifié ou token invalide
  /user/accounts/{accountId}/transactions:
    get:
      summary: Récupérer les transactions d'un compte
      description: Retourne la liste des transactions pour un compte utilisateur donné.
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID du compte bancaire
          schema:
            type: string
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non authentifié ou token invalide
        '404':
          description: Compte ou transactions non trouvés
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails complets d'une transaction spécifique.
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID du compte bancaire
          schema:
            type: string
        - name: transactionId
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Non authentifié ou token invalide
        '404':
          description: Transaction non trouvée
    patch:
      summary: Modifier une transaction (catégorie ou notes)
      description: Permet de modifier la catégorie ou les notes d'une transaction.
      tags:
        - Transactions
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID du compte bancaire
          schema:
            type: string
        - name: transactionId
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: Food
                notes:
                  type: string
                  example: Achat du matin
      responses:
        '200':
          description: Transaction modifiée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données invalides
        '401':
          description: Non authentifié ou token invalide
        '404':
          description: Transaction non trouvée
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          example: "2020-06-20"
        description:
          type: string
          example: Golden Sun Bakery
        amount:
          type: string
          example: "$5.00"
        balance:
          type: string
          example: "$2082.79"
        type:
          type: string
          example: Electronic
        category:
          type: string
          example: Food
        notes:
          type: string
          example: ""